### ISSUE TITLE
OSC Server handler

### ISSUE THREAD

**Issue by avlapp** [loffa/gosc#1]
Is it possible to make a osc server with gosc?

**Comment by loffa** [comment]
At the moment this is not implemented. However this can quite easily be added.

I will start working on it.

**Comment by avlap** [comment]
Nice, I might be the first tester ;)

Speaking about osc and liblo for c/ c++, it has some limitations it seems. You might want to try to avoid those limitations in your lib:

ipv6 support broken and it is disabled by default. 
liblo OSC server cannot be instructed to bind to a specific hostname or network interface. It binds to all available interfaces.

https://sourceforge.net/p/liblo/mailman/message/34989152/
http://liblo.sourceforge.net/docs/group__liblolowlevel.html#ga4afa474b11ed0d4511857ae79c56aaa1

Support for UDP, TCP and Unix sockets would be a good thing probably.

**Comment by loffa** [comment]
Implementation for now is using the UDP transport by default. This can also be extended with the Transport interface for TCP and Unix socket later.

**Comment by avlapp** [comment]
That was fast. Cool. I'll give it a go.

**Comment by avlapp** [comment]
I don't have any experience with Go, just a bit with Python, but a question comes up. In liblo (python-liblo) you've class Server and ServerThread:

" A server that can receive OSC messages using a simple single-threaded polling model. Use ServerThread for an OSC server that runs in its own thread and never blocks."
http://dsacre.github.io/pyliblo/doc/

How does that work in Go (and gosc)?

**Comment by loffa** [comment]
You should look in the `examples` directory where a OSC Server example is available. It shows how you kan create a handler for messages on the address `/hello` that responds with a string.

This works much like the `add_method` function in the py-lib.

**Comment by avlapp** [comment]
Any chance you could implement TCP? I'd like to do some experimentation.

**Comment by loffa** [comment]
This can be requested in a separate issue :)
