### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by avlapp** [loffa/gosc#12]
It's good practice to handle errors in main I've read. I'm wondering how to get errors from custom handler functions to main. This question could be related to the question about goroutines. (Not sure if comparable, but I saw the net/http package has a Error function.)

**Comment by loffa** [comment]
Errors in message handling can never be transferred all the way to main. Look at examples for the HTTP package and how error handling is kept inside of the handlers for requests.

**Comment by avlapp** [comment]
Thanks for your comments and explanations.
