### ISSUE TITLE
IPv4 / IPv6

### ISSUE THREAD

**Issue by avlapp** [loffa/gosc#13]
I'm wondering does gosc work with IPv4 or IPv6 or both? I've read some issues regarding ipv6 (multicasting?) for c/c++ libraries. (pure data does have it implemented https://github.com/pure-data/pure-data/blob/master/src/s_net.c).

Not sure if this is a issue for gosc/golang, but might be useful info.

**Comment by loffa** [comment]
Hey,

The server method `NewUDPListen` is used to open the listening port. It accept the listen address parameter with prefix, as it is calling the https://pkg.go.dev/net#ListenPacket function.

The same goes for the client using the Dial function https://pkg.go.dev/net#Dial
