### ISSUE TITLE
message handler: matching types

### ISSUE THREAD

**Issue by avlapp** [loffa/gosc#15]
In the liblo osc library one can add a osc message handler (osc Method) which also checks for types.

So "/foo", "fi" matches a different message then "/foo", "sis". 

As far as I understand gosc only checks for the address, "/error", not for the types.

In the go-osc package I found at least a function that returns the type tags as string I think:
https://github.com/hypebeast/go-osc/blob/cec5a8a1e5f5/osc/osc.go#L220

Liblo example and description: 

 /* add method that will match the path /foo/bar, with two numbers, coerced
     * to float and int */
    lo_server_thread_add_method(st, "/foo/bar", "fi", foo_handler, NULL);

https://github.com/radarsat1/liblo/blob/master/examples/example_server.c
https://github.com/radarsat1/liblo/blob/master/lo/lo_types.h

**Comment by loffa** [comment]
It is correct that gosc only matches on the address. Since the data arguments is already preparsed into the Arguments array of Message it could be done in the handler with some reflection.
