### ISSUE TITLE
Use of pointers

### ISSUE THREAD

**Issue by avlapp** [loffa/gosc#17]
As far as I understand it now, pointers should only be used when the method does modify something, see also 
https://github.com/scgolang/osc/issues/11

So for example:

func (m *Message) GetType() PackageType
func (m *Message) String() string

Shouldn't be a pointer I think.
I've seen some code where a osc message is send via a channel, in that case using a pointer might have the disadvantage that it isn't concurrency safe.

**Comment by loffa** [comment]
Receiver methods for the types needs to use pointer types to be available when the struct is used in a pointer context.
